### ISSUE TITLE
Activity stream does not show user uploaded photo, does not show thumbnail

### ISSUE THREAD

**Issue by dranii** [buddydev/mediapress#11]

**Comment by sbrajesh** [comment]
Hi,
Is it happening for uploads from activity screen? at the moment, the uploads from gallery screen does not add to activity. I am working on it.

**Comment by rwrobe** [comment]
I'm seeing this issue happen in the activity uploads form-- user uploads picture, ajax adds it to the DOM, then on refresh, it no longer appears.

**Comment by sbrajesh** [comment]
Hi,If a user does not post the activity, the media will not appear? The simple logic is like you do it on facebook. Upload media to activity and post the activity.
Since the user does not publish activity, the media is marked as orphan and does not appear.

Also, now the original issue in this topic is fixed and automatic publishing can be enabled/disabled from settings for gallery upload. Also, gallery uploads gives user option to publish media o activity.

**Comment by sbrajesh** [comment]
Hi @rwrobe ,
Have you had any chance to look at the above?

**Comment by rwrobe** [comment]
Hi @sbrajesh -- I think the issue I'm dealing with has little to do with MP but rather a set of complex customizations made to it, so it seems I'm going this one alone :) Thanks for your help anyway!

**Comment by rhisss** [comment]
Should not this be Closed issue ? This problem happens no more.

**Comment by sbrajesh** [comment]
Thank you. Marking it as closed.
