### ISSUE TITLE
HTTPS Issue

### ISSUE THREAD

**Issue by Ruddernation-Designs** [buddydev/mediapress#27]
I've just found that there is an issue with Mediapress and WordPress HTTPS,
Media uploads fail on frontend only when Force SSL Administration is enabled on WP HTTPS plugin.

**Comment by Ruddernation-Designs** [comment]
Also using define('FORCE_SSL_ADMIN', true); also makes the uploads fail.
An error occurred in the upload. Please try again later. is the displayed error.

**Comment by sbrajesh** [comment]
Hi Ben,
Thank you for reporting.
It will happen due to the Same origin security policy.

The uploader and the the handlers( end point) must use same protocol.

In your case, The upload handler( admin ajax) is using https while the uploader is not on a page using https protocol. So, That is happening.

Please have a look at this document
https://en.wikipedia.org/wiki/Same-origin_policy

I am not sure if we should consider it a bug and try to if it or not. Can you please check if it is happening when the upload page is also using https?

**Comment by Ruddernation-Designs** [comment]
Hi Brajesh,
Thanks for pointing that out,
I just didn't want groups to be served over https as that blocks content from external sources and some less savvy users wouldn't know to look for the blocked content,
I've since gave users a warning message of the blocked content but as each browser warns users in different ways this is a pain and will force some users to go else where.

**Comment by sbrajesh** [comment]
Hi Ben,
Closing this as there is nothing much we can do here.
