### ISSUE TITLE
Does mediapress use the new BP Attachments API?

### ISSUE THREAD

**Issue by landwire** [buddydev/mediapress#28]
Hi there,
I have not used MediaPress yet, but was wondering, if it makes use of the new BP Attachements API?
I guess it would make sense if it did, but then I am by no means an expert...

**Comment by sbrajesh** [comment]
Hi,
Thank you for asking.
No. It is not using and it won't use attachment API in future. The Attachment API is not best suitable for this type of application. In its current state, the attachment API is good for cover images, profile photos but managing complete site's media for a professional network is much more than that. When dealing with huge set of data, I believe sticking with WordPress core APIs is a much better thing.

MediaPress uses WordPress core APIs for upload and utilizes WordPress Media capabilities.
PS: Current version of MediaPress is not dependent on BuddyPress, so that was also one of the factors in choosing WordPress core API instead of BP dependent API.
Hope that clarifies.

**Comment by landwire** [comment]
Thanks for the quick reply and clarification. I definitely look into MediaPress should I need to use that functionality. I might even look into it to learn a bit how to handle media in WordPress. I have implemented the WP media uploader on the frontend some time ago, but it is very messy code! It works though :-)

**Comment by sbrajesh** [comment]
Thank you. Glad to know that you implemented the wp media uploader from front end :)

Will be happy to assist in case you plan to use MediaPress in any of your future projects :)
