### ISSUE TITLE
Upload panel AND Upload via Select File open together

### ISSUE THREAD

**Issue by valuser** [buddydev/mediapress#29]
This is a pretty awesome plugin - thank you!

Testing on a multisite local install with the newest version of everything inculding Kleo (premium) theme.

When the icons are clicked in any activity screen  the upload panel appears but the "select the file" option also immediately or simultaneously goes into action.

Otherwise all good so far.

Could well me inattention on my part re settings --- but haven't found it so far.

Any guidance much appreciated.

**Comment by valuser** [comment]
now tested also on a local single site, twenty fifteen theme, just buddypress and bbpress plugins all up-to-date versions

Same behavior as described above

**Comment by sbrajesh** [comment]
Hi Val,
Thank you.

That opening of the file chooser is intentional. You can see here I have simulated the click on the upload button to open that file chooser.
https://github.com/buddydev/mediapress/blob/master/assets/js/mpp.js#L157

The simple reason is we do not want the user to first click on the icon and thenwait for the drop area to appear then drop the files or click again to select file. In my personal view, the current way sound like more intuitive. 

PS: If you want to disable that behavior, It is possible to do via javascript code( No need to change core). I did it for one of my plugins for MediaPress, so if you need to disable it, please do let me know( I will favor not disabling that behavior).

Thank you
Brajesh

**Comment by valuser** [comment]
point taken. Thanks - and for your many many contributions.

**Comment by sbrajesh** [comment]
Thank you.
