### ISSUE TITLE
Adding Remote videos(Youtube/vimeo etc) via MediaPress

### ISSUE THREAD

**Issue by sbrajesh** [buddydev/mediapress#9]
The problem is that we are not sure how to provide the Ui for the display of these links on user profile. Adding is fine but should we create separate types for remote videos( Their player have different UI than the local hosted video) or keep them as mixed content in all the galleries ?

Please let us know your suggestions here.

**Comment by mourique** [comment]
I would prefer them to be mixed, the user shouldn't be concerned with where the media is coming from. There should be some kind of information that some media is external. maybe with favicon or something.

**Comment by 0x054** [comment]
Mixed content would be fine.  Personally it wouldn't bother me if the UI is different between videos uploaded locally and video hosted remotely.

**Comment by sbrajesh** [comment]
Hi @mourique , @IVIyg0t 
I understand that we should allow mix videos. The problem is youtube videos use a different player while vimeo will have its own player and that will be the case for most of the remote sites that host video. It may lead to a messed up gallery layout.

Another issue is activity, BuddyPress already supports embedding videos from sites that support oembed videos.

Should we allow users to add videos like facebook(scan the link from activity and add to the profile gallery) or add an icon to enter the url? It all makes it confusing for the end user and that is my concern.

**Comment by danielemezzetti** [comment]
I think that's almost impossible anyway to have a "neat" layout. Different screen sizes, different players, different WP themes... it's simply impossible. The gallery layout should be simple, and the end user will have to figure out things by himself.
For video embedding, my penny is that BP oembed is adequate already. Optional video link scan would be a nice addition, but Facebook-style page link is higher priority for me.

**Comment by abegit** [comment]
Why don't you try to use WordPress' default YouTube feature that automatically makes an embed out of a youtube url, i know that I've been able to insert urls into the Activity Form and they automatically turned into YouTube Videos.
[https://codex.wordpress.org/Embeds]

I guess the next thing would be a way to get a Thumbnail for video, and a database entry so that you can fetch them within MediaPress.

I found out (via a Theme) that you can get the Thumbnails for Youtube Videos just by inserting the video-id in the correct place. Here's the url and all it needs is the video-id for it to work.
http://img.youtube.com/vi/<?php echo $video ?>/hqdefault.jpg

Maybe RegEx could be used to find YouTube URLs — Found this in a jwPlayer script — haven't tested this yet, and its in javascript — you might want to find a way to do this in PHP? Anyways, Thanks for the MediaPress Framework
`b.isYouTube=function(b){return/^(http|\/\/).*(youtube\.com|youtu\.be)\/.+/.test(b)};b.youTubeID=function(b){try{return/v[=\/]([^?&]*)|youtu\.be\/([^?]*)|^([\w-]*)$/i.exec(b).slice(1).join("").replace("?",
"")}catch(a){return""}};`

**Comment by sbrajesh** [comment]
Thank you. The problem is those embed are not accounted in the media tables. Our goal is to provide uniform interface irrespective of media type/source. It is in our milestone for 1.1 and will be available in mid September.

Thank you
Brajesh

**Comment by mastershas** [comment]
Hi Brajesh,
I have a few suggestions. Let us say a people has given a Youtube url. We can simply get a thumbnail from url and show it as a thumbnail to end user. Now once people click on the image then we can start loading the youtube video there and replace the image with video. I don't know how much it is feasible but it can solve the problem of layouts.

**Comment by sbrajesh** [comment]
Marking as resolved. Have added the functionality now(Oembed as well as direct remote url).
